In [5]:
print("hi")
import numpy as np
# magnet facing upwards
pr=np.array([20,394,266.5]) # X:20.000 Y:394.000 Z:266.500
pl=np.array([478,380,277.5]) # X:478.000 Y:380.000 Z:277.500
pt=np.array([248,388,499.5]) # X:248.000 Y:388.000 Z:499.500

pcxz=(pr+pl)/2

print(pcxz)

hi
[249. 387. 272.]


In [6]:
pz = pt - pcxz
print(pz)

[ -1.    1.  227.5]


In [8]:
px = pr-pl
print(px)

[-458.   14.  -11.]


In [9]:
py = np.cross(px,pz)

In [10]:
py

array([  3196., 104206.,   -444.])

In [11]:
p_x = pr-pcxz
print(p_x)

[-229.     7.    -5.5]


In [12]:
p_z = pt-pcxz
print(p_z)

[ -1.    1.  227.5]


In [13]:
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)

[-0.02837384 -0.99957361  0.00689368]


In [14]:
probe_distance_from_tip = 2.05
centerpoint = pcxz+p_y*254 + p_y*probe_distance_from_tip
2.05
print(centerpoint)

[241.73487892 131.05917706 273.76512613]


In [ ]:
import numpy as np

center = np.array([100,100,100])
radius = 50
npoints = 5

x = np.linspace(center[0]-radius, center[0]+radius, 2*npoints)
y = np.linspace(center[1]-radius, center[1]+radius, 2*npoints)
z = np.linspace(center[2]-radius, center[2]+radius, 2*npoints)

xx, yy, zz = np.meshgrid(x,y,z)

res = (xx-center[0])**2+(yy-center[1])**2+(zz-center[2])**2<=radius**2
#print(np.shape(res))
#print(res)

it = np.nditer(res, flags=['f_index'])
for entry in it:
    if entry:
        pass
        #print(it.index)

for iz in range(len(z)):
    for iy in range(len(y)):
        for ix in range(len(x)):
            if res[ix,iy,iz]:
                print(f"{x[ix]}, {y[iy]}, {z[iz]}")