In [10]:
print("hi")
import numpy as np
# magnet facing upwards
pr=np.array([15.000,383.000,263.500]) # X:15.000 Y:383.000 Z:263.500
pl=np.array([474.000,383.000,273.500]) # X:474.000 Y:383.000 Z:273.500
pt=np.array([248.000,384.000,496.500]) #X:248.000 Y:384.000 Z:496.500

pcxz=(pr+pl)/2

print(pcxz)

hi
[244.5 383.  268.5]


In [11]:
pz = pt - pcxz
print(pz)

[  3.5   1.  228. ]


In [12]:
px = pr-pl
print(px)

[-459.    0.  -10.]


In [4]:
py = np.cross(px,pz)

In [5]:
py

array([ 1.00000e+01,  1.04617e+05, -4.59000e+02])

In [6]:
p_x = pr-pcxz
print(p_x)

[-229.5    0.    -5. ]


In [7]:
p_z = pt-pcxz
print(p_z)

[  3.5   1.  228. ]


In [8]:
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)

[ 0.00224969 -0.99997311  0.0069793 ]


In [9]:
probe_distance_from_tip = 2.05
centerpoint = pcxz+p_y*254 + p_y*probe_distance_from_tip
2.05
print(centerpoint)

[245.07603192 126.95688422 270.28704997]


In [ ]:
import numpy as np

center = np.array([100,100,100])
radius = 50
npoints = 5

x = np.linspace(center[0]-radius, center[0]+radius, 2*npoints)
y = np.linspace(center[1]-radius, center[1]+radius, 2*npoints)
z = np.linspace(center[2]-radius, center[2]+radius, 2*npoints)

xx, yy, zz = np.meshgrid(x,y,z)

res = (xx-center[0])**2+(yy-center[1])**2+(zz-center[2])**2<=radius**2
#print(np.shape(res))
#print(res)

it = np.nditer(res, flags=['f_index'])
for entry in it:
    if entry:
        pass
        #print(it.index)

for iz in range(len(z)):
    for iy in range(len(y)):
        for ix in range(len(x)):
            if res[ix,iy,iz]:
                print(f"{x[ix]}, {y[iy]}, {z[iz]}")