In [13]:
print("hi")
import numpy as np
# magnet facing backwards
pr=np.array([38.4,440,154]) #np.array([14.5, 437.5 ,130.5])
pl=np.array([499,432.6,166.2]) #np.array([473.5, 432, 141])
pt=np.array([270,439.2,388.4]) #np.array([246.5, 437, 364.5])

pcxz=(pr+pl)/2

print(pcxz)

hi
[268.7 436.3 160.1]


In [14]:
pz = pt - pcxz
print(pz)

[  1.3   2.9 228.3]


In [15]:
px = pr-pl
print(px)

[-460.6    7.4  -12.2]


In [16]:
py = np.cross(px,pz)

In [17]:
py

array([  1724.8 , 105139.12,  -1345.36])

In [18]:
p_x = pr-pcxz
print(p_x)

[-230.3    3.7   -6.1]


In [19]:
p_z = pt-pcxz
print(p_z)

[  1.3   2.9 228.3]


In [20]:
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)

[-0.0139042  -0.99979999  0.01437553]


In [21]:
centerpoint = pcxz+p_y*254
print(centerpoint)

[265.16833365 182.35080288 163.7513855 ]


In [30]:
import numpy as np

center = np.array([100,100,100])
radius = 50
npoints = 5

x = np.linspace(center[0]-radius, center[0]+radius, 2*npoints)
y = np.linspace(center[1]-radius, center[1]+radius, 2*npoints)
z = np.linspace(center[2]-radius, center[2]+radius, 2*npoints)

xx, yy, zz = np.meshgrid(x,y,z)

res = (xx-center[0])**2+(yy-center[1])**2+(zz-center[2])**2<=radius**2
#print(np.shape(res))
#print(res)

it = np.nditer(res, flags=['f_index'])
for entry in it:
    if entry:
        pass
        #print(it.index)

for iz in range(len(z)):
    for iy in range(len(y)):
        for ix in range(len(x)):
            if res[ix,iy,iz]:
                print(f"{x[ix]}, {y[iy]}, {z[iz]}")

(10, 10, 10)
94.44444444444444, 72.22222222222223, 61.111111111111114
105.55555555555556, 72.22222222222223, 61.111111111111114
83.33333333333333, 83.33333333333333, 61.111111111111114
94.44444444444444, 83.33333333333333, 61.111111111111114
105.55555555555556, 83.33333333333333, 61.111111111111114
116.66666666666666, 83.33333333333333, 61.111111111111114
72.22222222222223, 94.44444444444444, 61.111111111111114
83.33333333333333, 94.44444444444444, 61.111111111111114
94.44444444444444, 94.44444444444444, 61.111111111111114
105.55555555555556, 94.44444444444444, 61.111111111111114
116.66666666666666, 94.44444444444444, 61.111111111111114
127.77777777777777, 94.44444444444444, 61.111111111111114
72.22222222222223, 105.55555555555556, 61.111111111111114
83.33333333333333, 105.55555555555556, 61.111111111111114
94.44444444444444, 105.55555555555556, 61.111111111111114
105.55555555555556, 105.55555555555556, 61.111111111111114
116.66666666666666, 105.55555555555556, 61.111111111111114
127.7