In [3]:
print("hi")
import numpy as np
pr=np.array([14.5, 437.5 ,130.5])
pl=np.array([473.5, 432, 141])
pt=np.array([246.5, 437, 364.5])

pcxz=(pr+pl)/2

print(pcxz)

hi
[244.   434.75 135.75]


In [10]:
pz = pt - pcxz
print(pz)

[  2.5    2.25 228.75]


In [7]:
px = pr-pl
print(px)

[-459.     5.5  -10.5]


In [8]:
py = np.cross(px,pz)

In [9]:
py

array([  1281.75, 104970.  ,  -1046.5 ])

In [11]:
p_x = pr-pcxz
print(p_x)

[-229.5     2.75   -5.25]


In [12]:
p_z = pt-pcxz
print(p_z)

[  2.5    2.25 228.75]


In [32]:
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)

[-0.00992615 -0.99988679  0.0113083 ]


In [34]:
centerpoint = pcxz+p_y*254
print(centerpoint)

[241.47875803 180.77875521 138.62230866]
