In [13]:
print("hi")
import numpy as np
# magnet facing backwards
pr=np.array([38.4,440,154]) #np.array([14.5, 437.5 ,130.5])
pl=np.array([499,432.6,166.2]) #np.array([473.5, 432, 141])
pt=np.array([270,439.2,388.4]) #np.array([246.5, 437, 364.5])

pcxz=(pr+pl)/2

print(pcxz)

hi
[268.7 436.3 160.1]


In [14]:
pz = pt - pcxz
print(pz)

[  1.3   2.9 228.3]


In [15]:
px = pr-pl
print(px)

[-460.6    7.4  -12.2]


In [16]:
py = np.cross(px,pz)

In [17]:
py

array([  1724.8 , 105139.12,  -1345.36])

In [18]:
p_x = pr-pcxz
print(p_x)

[-230.3    3.7   -6.1]


In [19]:
p_z = pt-pcxz
print(p_z)

[  1.3   2.9 228.3]


In [20]:
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)

[-0.0139042  -0.99979999  0.01437553]


In [21]:
centerpoint = pcxz+p_y*254
print(centerpoint)

[265.16833365 182.35080288 163.7513855 ]
