In [3]:
print("hi")
import numpy as np
# magnet facing backwards
pr=np.array([33.000,420.6,154.50])#np.array([32,432,152.5]) #np.array([38.4,440,154]) #np.array([14.5, 437.5 ,130.5])
pl=np.array([492.500,424.100,165.700])#np.array([491,436.5,164]) #np.array([499,432.6,166.2]) #np.array([473.5, 432, 141])
pt=np.array([,,])#np.array([264.4,436.1,386]) #np.array([270,439.2,388.4]) #np.array([246.5, 437, 364.5])

pcxz=(pr+pl)/2

print(pcxz)

hi
[261.5  434.25 158.25]


In [4]:
pz = pt - pcxz
print(pz)

[  2.9    1.85 227.75]


In [5]:
px = pr-pl
print(px)

[-459.    -4.5  -11.5]


In [6]:
py = np.cross(px,pz)

In [7]:
py

array([ -1003.6, 104503.9,   -836.1])

In [8]:
p_x = pr-pcxz
print(p_x)

[-229.5    -2.25   -5.75]


In [9]:
p_z = pt-pcxz
print(p_z)

[  2.9    1.85 227.75]


In [10]:
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)

[ 0.01215483 -0.99988049  0.00955352]


In [11]:
centerpoint = pcxz+p_y*254
print(centerpoint)

[264.58732658 180.28035603 160.6765933 ]


In [ ]:
import numpy as np

center = np.array([100,100,100])
radius = 50
npoints = 5

x = np.linspace(center[0]-radius, center[0]+radius, 2*npoints)
y = np.linspace(center[1]-radius, center[1]+radius, 2*npoints)
z = np.linspace(center[2]-radius, center[2]+radius, 2*npoints)

xx, yy, zz = np.meshgrid(x,y,z)

res = (xx-center[0])**2+(yy-center[1])**2+(zz-center[2])**2<=radius**2
#print(np.shape(res))
#print(res)

it = np.nditer(res, flags=['f_index'])
for entry in it:
    if entry:
        pass
        #print(it.index)

for iz in range(len(z)):
    for iy in range(len(y)):
        for ix in range(len(x)):
            if res[ix,iy,iz]:
                print(f"{x[ix]}, {y[iy]}, {z[iz]}")